#!/usr/bin/env python

import sys
import urllib

from lxml.html import parse, tostring
from lxml.cssselect import CSSSelector

BASE_URL = 'http://road.cc'

def main():
    root = GET('/review-archive')

    data = []

    for x in findall(root, '#block-roadcc_blocks-review_taxonomy'):
        row = []

        for child in findall(x, 'li a'):
            row.append((child.text, section(child.get('href'))))

        data.append((find(x, '.fieldset-title').text, row))

    from pprint import pprint
    pprint(data)

    return 0

def get_section(url):
    root = GET(url)

    result = []

    for x in findall(root, '.review-archive'):
        stars = find(x, '.review-stars img').get('src')
        rating = int(stars.split('-', 1)[1].split('.')[0])

        if rating < 9:
            continue

        title = find(x, '.review-title a')

        result.append({
            'url': '%s%s' % (BASE_URL, title.get('href')),
            'title': title.text,
            'price': float(find(x, '.review-price').text[1:]),
            'rating': rating,
        })

    return result

def GET(suffix):
    url = '%s%s' % (BASE_URL, suffix)

    print >>sys.stderr, "I: Downloading %s" % url

    return parse(urllib.urlopen(url))

def findall(elem, selector):
    return CSSSelector(selector)(elem)

def find(elem, selector):
    return findall(elem, selector)[0]

if __name__ == '__main__':
    sys.exit(main())
